// ----------------------------------------------------------------------

export const company = [
  'Bách hóa xanh',
  'của hàng tiện lợi Winmart',
  'của hàng tiện lợi Winmart',
  'của hàng tiện lợi Winmart',
  'Bách hóa xanh',
  'Bách hóa xanh',
  'của hàng tiện lợi Winmart',
  'của hàng tiện lợi Winmart',
  'của hàng tiện lợi GS 25',
  'của hàng tiện lợi GS 25',
  'của hàng tiện lợi GS 25',
  'của hàng tiện lợi GS 25',
  'của hàng tiện lợi GS 25',
  'Dare - Treutel',
  'Điện máy xanh',
  'Nolan - Kunde',
  'TNHH Thiên Hòa',
  'Dibbert Inc',
  'Goyette and Sons',
  'Feest Group',
  'TNHH Hòa Bình',
  'Bách hóa xanh test',
  'GS 25',
  'Bách hóa xanh test',
  'Hills - Mitchell',
  'GS 25',
  'GS 25',
  'Schmitt Inc',
  'Breitenberg - Rosenbaum',
  "O'Keefe, Schneider and Mraz",
  'Rohan, Langworth and Kling',
  'Morar and Sons',
  'Mraz LLC',
  'Rowe, Parisian and Kub',
  'Marquardt - Hane',
  'Medhurst Group',
  'Nikolaus - Lang',
  'Effertz, Mohr and Olson',
  'Anderson - Kris',
  'Runolfsson Group'
];
