// ----------------------------------------------------------------------

export const role = [
  'Frontend Developer',
  'Tester',
  'doanh nghiệp',
  'Mobile Developer',
  'doanh nghiệp',
  'Project Manager',
  'Leader',
  'doanh nghiệp',
  'Project Manager',
  'doanh nghiệp',
  'doanh nghiệp',
  'doanh nghiệp',
  'doanh nghiệp',
  'doanh nghiệp',
  'doanh nghiệp',
  'Front End Developer',
  'doanh nghiệp',
  'Full Stack Designer',
  'Full Stack Developer',
  'doanh nghiệp',
  'doanh nghiệp',
  'doanh nghiệp',
  'Project Manager',
  'doanh nghiệp',
  'doanh nghiệp',
  'Project Manager',
  'Full Stack Developer',
  'Hr Manager',
  'Hr Manager',
  'doanh nghiệp',
  'Project Manager',
  'Full Stack Designer',
  'doanh nghiệp',
  'Leader',
  'Front End Developer',
  'doanh nghiệp',
  'Project Manager',
  'doanh nghiệp',
  'doanh nghiệp',
  'Full Stack Designer'
];
