// ----------------------------------------------------------------------

export const title = [
  'Apply These 7 Secret Techniques To Improve Event',
  'Believing These 7 Myths About Event Keeps You From Growing',
  "Don't Waste Time! 7 Facts Until You Reach Your Event",
  'How 7 Things Will Change The Way You Approach Event',
  "Event Awards: 7 Reasons Why They Don't Work & What You Can Do About It",
  "Event Doesn't Have To Be Hard. Read These 7 Tips",
  'Event Is Your Worst Enemy. 7 Ways To Defeat It',
  'Event On A Budget: 7 Tips From The Great Depression',
  'Knowing These 7 Secrets Will Make Your Event Look Amazing',
  'Master The Art Of Event With These 7 Tips',
  'My Life, My Job, My Career: How 7 Simple Event Helped Me Succeed',
  'Take Advantage Of Event - Read These 7 Tips',
  'The Next 7 Things You Should Do For Event Success',
  'The Time Is Running Out! Think About These 7 Ways To Change Your Event',
  'The 7 Best Things About Event',
  'The 7 Biggest Event Mistakes You Can Easily Avoid',
  'The 7 Most Successful Event Companies In Region',
  'Think Your Event Is Safe? 7 Ways You Can Lose It Today',
  "Thinking About Event? 7 Reasons Why It's Time To Stop!",
  '7 Places To Get Deals On Event',
  'Best Event Android Apps',
  'Best Event Tips You Will Read This Year',
  'Best 30 Tips For Event',
  'Should Fixing Event Take 30 Steps?',
  'The A - Z Of Event',
  'The Next 30 Things To Immediately Do About Event',
  'The Ultimate Guide To Event',
  'Top 30 Funny Event Quotes',
  'Top 30 Quotes On Event',
  'Top 7 Lessons About Event To Learn Before You Hit 30',
  'Top 7 Ways To Buy A Used Event',
  '30 Best Ways To Sell Event',
  '30 Ideas For Event',
  '30 Lessons About Event You Need To Learn Before You Hit 40',
  '30 Methods Of Event Domination',
  '30 Things To Do Immediately About Event',
  '30 Tips To Grow Your Event',
  '30 Ways To Avoid Event Burnout',
  '30 Ways To Improve Event',
  'How To Make More Event By Doing Less'
];

export const sentence = [
  'Assumenda nam repudiandae rerum fugiat vel maxime.',
  'Quis veniam aut saepe aliquid nulla.',
  'Reprehenderit ut voluptas sapiente ratione nostrum est.',
  'Error ut sit vel molestias velit.',
  'Quo quia sit nihil nemo doloremque et.',
  'Autem doloribus harum vero laborum.',
  'Tempora officiis consequuntur architecto nostrum autem nam adipisci.',
  'Voluptas sunt magni adipisci praesentium saepe.',
  'Ea architecto quas voluptates voluptas earum illo est vel rem.',
  'Ipsum expedita reiciendis ut.',
  'Architecto vel voluptatibus alias a aut non maxime ipsa voluptates.',
  'Reiciendis enim officiis cupiditate eaque distinctio laudantium modi similique consequatur.',
  'Ab autem consequatur itaque mollitia ipsum cupiditate error repudiandae nobis.',
  'Distinctio architecto debitis eligendi consequatur unde id modi accusantium possimus.',
  'At ut voluptate accusantium.',
  'Repudiandae ut qui veritatis sint.',
  'Laboriosam blanditiis quo sed et qui esse ipsam necessitatibus sed.',
  'Et molestiae et excepturi maxime omnis.',
  'Sint dolorem quam eum magnam.',
  'Rerum ut iusto iste quam voluptatem necessitatibus.',
  'Et quam in.',
  'Fugit esse tenetur.',
  'Dolorem dolor porro nihil cupiditate molestiae deserunt ut.',
  'Omnis beatae eos eius aut molestias laboriosam laborum et optio.',
  'Ut veniam quam assumenda ut voluptatibus ducimus accusamus.',
  'Quos dignissimos neque omnis reiciendis voluptatem ducimus.',
  'Laboriosam quia ut esse.',
  'Sit reiciendis nihil qui molestias et.',
  'Facilis cupiditate minima ratione quaerat omnis velit non ex totam.',
  'Provident sint esse voluptatem voluptas eveniet est.',
  'Molestias consequatur ea facilis.',
  'Tempora voluptatibus autem ut ut porro quae delectus dolorum.',
  'Et consequatur amet nemo ducimus voluptatem placeat voluptas.',
  'Modi iste atque hic voluptas sit quis deleniti quas consequatur.',
  'Omnis est aliquid odio mollitia aliquid ex.',
  'Officia possimus veniam quod molestias.',
  'Mollitia inventore recusandae provident aut.',
  'Numquam ullam beatae possimus.',
  'Fuga velit cupiditate ex culpa odio aut ut.',
  'Vero corrupti nam voluptatum excepturi est et.'
];

export const description = [
  'Đây tuy là một khái niệm còn khá xa lạ với người Việt Nam nhưng với những người có hiểu biết về chuyên ngành Kinh tế hoặc đang nghiên cứu về nó chắc chắn đã phải từng nghe qua.',
  'Bất cứ ai cũng đều có thể trở thành nhà đầu tư trên nền tảng Krowd, chỉ cần bạn có được số tiền yêu cầu tối thiểu trong ví đầu tư, những phi vụ đầu tư tốt nhất sẽ tự tìm đến bạn.',
  'Để có thể được xuất hiện trên Krowd, mỗi dự án đều phải trải qua những vòng kiểm định nghiêm ngặc để chứng minh được mức độ đáng tin và cả những lợi ích mà dự án sẽ mang đến cho các nhà đầu tư.'
];
export const header2 = [
  '+ Khái niệm “Đầu tư vay vốn” có phổ biến ở Việt Nam không?',
  '+ Ai có thể trở thành nhà đầu tư trên Krowd?',
  '+ Các thương vụ ở Krowd có đáng tin tưởng để đầu tư vào không?'
];
